name: CI
on: [push]
jobs:
  build:
    name: Build, lint

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ["20.x"]
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps
        run: yarn install

      - name: Lint
        id: lint
        run: yarn lint

      - name: Build
        id: build
        run: yarn build
